# Generated by Django 2.1.4 on 2018-12-19 03:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 19, 3, 39, 52, 375392, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
